export const fields = [
    {
      id: "Nombre",
      label: "Nombre de la Organización*",
      helperText: "Se visualizará en el título de la publicación",
      type: "text",
      defaultValue: "Lavanda",
    },
    {
      id: "Descripcion",
      label: "Descripción",
      helperText: "Se visualizará en el subtítulo de la publicación 0/50",
      type: "text",
      defaultValue: "Cosmética natural",
    },
    {
      id: "Categoria",
      label: "Categoría*",
      helperText: "Seleccioná la categoría de tu Producto/Servicio",
      type: "select",
      options: [
        "Bienestar",
        "Capacitaciones",
        "Construcción",
        "Cultivos",
        "Gastronomía",
        "Indumentaria",
        "Merchandising",
        "Muebles/Deco",
        "Reciclaje",
        "Tecnología",
        "Transporte",
      ],
      defaultValue: "Bienestar",
    },
    {
      id: "Correo",
      label: "Correo electrónico*",
      helperText: "El mismo con el que te registraste o uno diferente",
      type: "text",
      defaultValue: "lavandacosmetica@gmail.com",
    },
    {
      id: "Telefono",
      label: "Teléfono o Whatsapp*",
      helperText: "Con el siguiente formato +54 9 261 002 002",
      type: "text",
      defaultValue: "+54 9 261 568 258",
    },
    {
      id: "Instagram",
      label: "Instagram*",
      helperText: "Podés pegar el link de tu perfil",
      type: "text",
      defaultValue: "https://www.instagram.com/lavandacosmética/",
    },
    {
      id: "Facebook",
      label: "Facebook*",
      helperText: "Podés pegar el link de tu perfil",
      type: "text",
      defaultValue: "Facebook",
    },
    {
      id: "País",
      label: "País*",
      helperText: "Seleccioná un País de la lista",
      type: "select",
      options: ["Argentina", "Chile", "Colombia", "Uruguay"],
      defaultValue: "Argentina",
    },
    {
      id: "Provincia",
      label: "Provincia/Estado*",
      helperText: "Seleccioná un Provincia/Estado de la lista",
      type: "select",
      options: ["Buenos Aires", "Córdoba", "Mendoza", "San Luis"],
      defaultValue: "Mendoza",
    },
    {
      id: "Ciudad",
      label: "Ciudad*",
      helperText: "Sin abreviaturas, nombre completo",
      type: "text",
      defaultValue: "Godoy Cruz",
    },
    {
      id: "Descripcion del producto",
      label: "Descripción del Producto/Servicio*",
      helperText: "Máximo 300 caracteres 300/300",
      type: "text",
      defaultValue:
        "Lavanda es un proyecto familiar. Perseguimos una cosmética efectiva, magistral y con personalidad. Nuestro objetivo es hacer productos que enamoren, que cuiden al planeta, con principios activos que dejen el pelo sano y la piel bella.",
    },
  ];